# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'wews.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_wews(object):
    def setupUi(self, wews):
        if not wews.objectName():
            wews.setObjectName(u"wews")
        wews.resize(420, 840)
        wews.setMinimumSize(QSize(420, 840))
        wews.setMaximumSize(QSize(420, 840))
        font = QFont()
        font.setFamily(u"\u65b9\u6b63\u7c97\u9ed1\u5b8b\u7b80\u4f53")
        wews.setFont(font)
        self.centralwidget = QWidget(wews)
        self.centralwidget.setObjectName(u"centralwidget")
        self.lb_bg = QLabel(self.centralwidget)
        self.lb_bg.setObjectName(u"lb_bg")
        self.lb_bg.setGeometry(QRect(0, -5, 420, 840))
        self.lb_bg.setMinimumSize(QSize(420, 840))
        self.lb_bg.setMaximumSize(QSize(420, 840))
        self.lb_bg.setPixmap(QPixmap(u"builds/bg.png"))
        self.lb_bg.setScaledContents(True)
        self.lb_start = QLabel(self.centralwidget)
        self.lb_start.setObjectName(u"lb_start")
        self.lb_start.setEnabled(True)
        self.lb_start.setGeometry(QRect(600, 320, 300, 60))
        self.lb_start.setMinimumSize(QSize(0, 0))
        self.lb_start.setCursor(QCursor(Qt.ArrowCursor))
        self.lb_start.setPixmap(QPixmap(u"builds/WEWS.png"))
        self.lb_start.setScaledContents(True)
        self.g1 = QGroupBox(self.centralwidget)
        self.g1.setObjectName(u"g1")
        self.g1.setGeometry(QRect(10, 10, 400, 110))
        self.g1.setMinimumSize(QSize(400, 110))
        self.g1.setMaximumSize(QSize(400, 110))
        font1 = QFont()
        font1.setFamily(u"\u5fae\u8f6f\u96c5\u9ed1 Light")
        self.g1.setFont(font1)
        self.lb_g1_left = QLabel(self.g1)
        self.lb_g1_left.setObjectName(u"lb_g1_left")
        self.lb_g1_left.setGeometry(QRect(30, 30, 60, 60))
        self.lb_g1_left.setMinimumSize(QSize(55, 55))
        self.lb_g1_left.setMaximumSize(QSize(70, 70))
        self.lb_g1_left.setScaledContents(True)
        self.lb_g1_middle = QLabel(self.g1)
        self.lb_g1_middle.setObjectName(u"lb_g1_middle")
        self.lb_g1_middle.setGeometry(QRect(110, 20, 170, 81))
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lb_g1_middle.sizePolicy().hasHeightForWidth())
        self.lb_g1_middle.setSizePolicy(sizePolicy)
        self.lb_g1_middle.setMinimumSize(QSize(170, 70))
        self.lb_g1_middle.setMaximumSize(QSize(171, 90))
        self.lb_g1_middle.setScaledContents(True)
        self.lb_g1_middle.setWordWrap(True)
        self.lb_g1_right = QLabel(self.g1)
        self.lb_g1_right.setObjectName(u"lb_g1_right")
        self.lb_g1_right.setGeometry(QRect(310, 40, 50, 50))
        self.lb_g1_right.setMinimumSize(QSize(50, 50))
        self.lb_g1_right.setMaximumSize(QSize(70, 70))
        self.lb_g1_right.setScaledContents(True)
        self.lb_g1_bg = QLabel(self.g1)
        self.lb_g1_bg.setObjectName(u"lb_g1_bg")
        self.lb_g1_bg.setGeometry(QRect(0, 19, 400, 90))
        self.lb_g1_bg.setMinimumSize(QSize(400, 90))
        self.lb_g1_bg.setMaximumSize(QSize(400, 110))
        self.lb_g1_bg.setScaledContents(True)
        self.lb_g1_bg.raise_()
        self.lb_g1_left.raise_()
        self.lb_g1_middle.raise_()
        self.lb_g1_right.raise_()
        self.g2 = QGroupBox(self.centralwidget)
        self.g2.setObjectName(u"g2")
        self.g2.setGeometry(QRect(10, 120, 400, 110))
        self.g2.setMinimumSize(QSize(400, 110))
        self.g2.setMaximumSize(QSize(400, 110))
        self.g2.setFont(font1)
        self.lb_g2_left = QLabel(self.g2)
        self.lb_g2_left.setObjectName(u"lb_g2_left")
        self.lb_g2_left.setGeometry(QRect(30, 30, 60, 60))
        self.lb_g2_left.setMinimumSize(QSize(55, 55))
        self.lb_g2_left.setMaximumSize(QSize(70, 70))
        self.lb_g2_left.setScaledContents(True)
        self.lb_g2_middle = QLabel(self.g2)
        self.lb_g2_middle.setObjectName(u"lb_g2_middle")
        self.lb_g2_middle.setGeometry(QRect(110, 20, 170, 81))
        sizePolicy.setHeightForWidth(self.lb_g2_middle.sizePolicy().hasHeightForWidth())
        self.lb_g2_middle.setSizePolicy(sizePolicy)
        self.lb_g2_middle.setMinimumSize(QSize(170, 70))
        self.lb_g2_middle.setMaximumSize(QSize(170, 90))
        self.lb_g2_middle.setScaledContents(True)
        self.lb_g2_middle.setWordWrap(True)
        self.lb_g2_right = QLabel(self.g2)
        self.lb_g2_right.setObjectName(u"lb_g2_right")
        self.lb_g2_right.setGeometry(QRect(310, 40, 50, 50))
        self.lb_g2_right.setMinimumSize(QSize(50, 50))
        self.lb_g2_right.setMaximumSize(QSize(70, 70))
        self.lb_g2_right.setScaledContents(True)
        self.lb_g2_bg = QLabel(self.g2)
        self.lb_g2_bg.setObjectName(u"lb_g2_bg")
        self.lb_g2_bg.setGeometry(QRect(0, 19, 400, 90))
        self.lb_g2_bg.setMinimumSize(QSize(400, 90))
        self.lb_g2_bg.setMaximumSize(QSize(400, 110))
        self.lb_g2_bg.setScaledContents(True)
        self.lb_g2_bg.raise_()
        self.lb_g2_left.raise_()
        self.lb_g2_middle.raise_()
        self.lb_g2_right.raise_()
        self.g3 = QGroupBox(self.centralwidget)
        self.g3.setObjectName(u"g3")
        self.g3.setGeometry(QRect(10, 230, 400, 110))
        self.g3.setMinimumSize(QSize(400, 110))
        self.g3.setMaximumSize(QSize(400, 110))
        self.g3.setFont(font1)
        self.lb_g3_left = QLabel(self.g3)
        self.lb_g3_left.setObjectName(u"lb_g3_left")
        self.lb_g3_left.setGeometry(QRect(30, 30, 60, 60))
        self.lb_g3_left.setMinimumSize(QSize(55, 55))
        self.lb_g3_left.setMaximumSize(QSize(70, 70))
        self.lb_g3_left.setScaledContents(True)
        self.lb_g3_middle = QLabel(self.g3)
        self.lb_g3_middle.setObjectName(u"lb_g3_middle")
        self.lb_g3_middle.setGeometry(QRect(110, 20, 170, 81))
        sizePolicy.setHeightForWidth(self.lb_g3_middle.sizePolicy().hasHeightForWidth())
        self.lb_g3_middle.setSizePolicy(sizePolicy)
        self.lb_g3_middle.setMinimumSize(QSize(170, 70))
        self.lb_g3_middle.setMaximumSize(QSize(170, 90))
        self.lb_g3_middle.setScaledContents(True)
        self.lb_g3_middle.setWordWrap(True)
        self.lb_g3_right = QLabel(self.g3)
        self.lb_g3_right.setObjectName(u"lb_g3_right")
        self.lb_g3_right.setGeometry(QRect(310, 40, 50, 50))
        self.lb_g3_right.setMinimumSize(QSize(50, 50))
        self.lb_g3_right.setMaximumSize(QSize(70, 70))
        self.lb_g3_right.setScaledContents(True)
        self.lb_g3_bg = QLabel(self.g3)
        self.lb_g3_bg.setObjectName(u"lb_g3_bg")
        self.lb_g3_bg.setGeometry(QRect(0, 19, 400, 90))
        self.lb_g3_bg.setMinimumSize(QSize(400, 90))
        self.lb_g3_bg.setMaximumSize(QSize(400, 110))
        self.lb_g3_bg.setScaledContents(True)
        self.lb_g3_bg.raise_()
        self.lb_g3_left.raise_()
        self.lb_g3_middle.raise_()
        self.lb_g3_right.raise_()
        self.g4 = QGroupBox(self.centralwidget)
        self.g4.setObjectName(u"g4")
        self.g4.setGeometry(QRect(10, 340, 400, 110))
        self.g4.setMinimumSize(QSize(400, 110))
        self.g4.setMaximumSize(QSize(400, 110))
        self.g4.setFont(font1)
        self.lb_g4_left = QLabel(self.g4)
        self.lb_g4_left.setObjectName(u"lb_g4_left")
        self.lb_g4_left.setGeometry(QRect(30, 30, 60, 60))
        self.lb_g4_left.setMinimumSize(QSize(55, 55))
        self.lb_g4_left.setMaximumSize(QSize(70, 70))
        self.lb_g4_left.setScaledContents(True)
        self.lb_g4_middle = QLabel(self.g4)
        self.lb_g4_middle.setObjectName(u"lb_g4_middle")
        self.lb_g4_middle.setGeometry(QRect(110, 20, 170, 81))
        sizePolicy.setHeightForWidth(self.lb_g4_middle.sizePolicy().hasHeightForWidth())
        self.lb_g4_middle.setSizePolicy(sizePolicy)
        self.lb_g4_middle.setMinimumSize(QSize(170, 70))
        self.lb_g4_middle.setMaximumSize(QSize(170, 90))
        self.lb_g4_middle.setScaledContents(True)
        self.lb_g4_middle.setWordWrap(True)
        self.lb_g4_right = QLabel(self.g4)
        self.lb_g4_right.setObjectName(u"lb_g4_right")
        self.lb_g4_right.setGeometry(QRect(310, 40, 50, 50))
        self.lb_g4_right.setMinimumSize(QSize(50, 50))
        self.lb_g4_right.setMaximumSize(QSize(70, 70))
        self.lb_g4_right.setScaledContents(True)
        self.lb_g4_bg = QLabel(self.g4)
        self.lb_g4_bg.setObjectName(u"lb_g4_bg")
        self.lb_g4_bg.setGeometry(QRect(0, 19, 400, 90))
        self.lb_g4_bg.setMinimumSize(QSize(400, 90))
        self.lb_g4_bg.setMaximumSize(QSize(400, 110))
        self.lb_g4_bg.setScaledContents(True)
        self.lb_g4_bg.raise_()
        self.lb_g4_left.raise_()
        self.lb_g4_middle.raise_()
        self.lb_g4_right.raise_()
        self.pbtn_last = QPushButton(self.centralwidget)
        self.pbtn_last.setObjectName(u"pbtn_last")
        self.pbtn_last.setGeometry(QRect(330, 790, 30, 30))
        self.pbtn_last.setMinimumSize(QSize(30, 30))
        self.pbtn_last.setMaximumSize(QSize(30, 30))
        self.g5 = QGroupBox(self.centralwidget)
        self.g5.setObjectName(u"g5")
        self.g5.setGeometry(QRect(10, 450, 400, 110))
        self.g5.setMinimumSize(QSize(400, 110))
        self.g5.setMaximumSize(QSize(400, 110))
        self.g5.setFont(font1)
        self.lb_g5_left = QLabel(self.g5)
        self.lb_g5_left.setObjectName(u"lb_g5_left")
        self.lb_g5_left.setGeometry(QRect(30, 30, 60, 60))
        self.lb_g5_left.setMinimumSize(QSize(55, 55))
        self.lb_g5_left.setMaximumSize(QSize(70, 70))
        self.lb_g5_left.setScaledContents(True)
        self.lb_g5_middle = QLabel(self.g5)
        self.lb_g5_middle.setObjectName(u"lb_g5_middle")
        self.lb_g5_middle.setGeometry(QRect(110, 20, 170, 81))
        sizePolicy.setHeightForWidth(self.lb_g5_middle.sizePolicy().hasHeightForWidth())
        self.lb_g5_middle.setSizePolicy(sizePolicy)
        self.lb_g5_middle.setMinimumSize(QSize(170, 70))
        self.lb_g5_middle.setMaximumSize(QSize(170, 90))
        self.lb_g5_middle.setScaledContents(True)
        self.lb_g5_middle.setWordWrap(True)
        self.lb_g5_right = QLabel(self.g5)
        self.lb_g5_right.setObjectName(u"lb_g5_right")
        self.lb_g5_right.setGeometry(QRect(310, 40, 50, 50))
        self.lb_g5_right.setMinimumSize(QSize(50, 50))
        self.lb_g5_right.setMaximumSize(QSize(70, 70))
        self.lb_g5_right.setScaledContents(True)
        self.lb_g5_bg = QLabel(self.g5)
        self.lb_g5_bg.setObjectName(u"lb_g5_bg")
        self.lb_g5_bg.setGeometry(QRect(0, 19, 400, 90))
        self.lb_g5_bg.setMinimumSize(QSize(400, 90))
        self.lb_g5_bg.setMaximumSize(QSize(400, 110))
        self.lb_g5_bg.setScaledContents(True)
        self.lb_g5_bg.raise_()
        self.lb_g5_left.raise_()
        self.lb_g5_middle.raise_()
        self.lb_g5_right.raise_()
        self.g6 = QGroupBox(self.centralwidget)
        self.g6.setObjectName(u"g6")
        self.g6.setGeometry(QRect(10, 560, 400, 110))
        self.g6.setMinimumSize(QSize(400, 110))
        self.g6.setMaximumSize(QSize(400, 110))
        self.g6.setFont(font1)
        self.lb_g6_left = QLabel(self.g6)
        self.lb_g6_left.setObjectName(u"lb_g6_left")
        self.lb_g6_left.setGeometry(QRect(30, 30, 60, 60))
        self.lb_g6_left.setMinimumSize(QSize(55, 55))
        self.lb_g6_left.setMaximumSize(QSize(70, 70))
        self.lb_g6_left.setScaledContents(True)
        self.lb_g6_middle = QLabel(self.g6)
        self.lb_g6_middle.setObjectName(u"lb_g6_middle")
        self.lb_g6_middle.setGeometry(QRect(110, 20, 170, 81))
        sizePolicy.setHeightForWidth(self.lb_g6_middle.sizePolicy().hasHeightForWidth())
        self.lb_g6_middle.setSizePolicy(sizePolicy)
        self.lb_g6_middle.setMinimumSize(QSize(170, 70))
        self.lb_g6_middle.setMaximumSize(QSize(170, 90))
        self.lb_g6_middle.setScaledContents(True)
        self.lb_g6_middle.setWordWrap(True)
        self.lb_g6_right = QLabel(self.g6)
        self.lb_g6_right.setObjectName(u"lb_g6_right")
        self.lb_g6_right.setGeometry(QRect(310, 40, 50, 50))
        self.lb_g6_right.setMinimumSize(QSize(50, 50))
        self.lb_g6_right.setMaximumSize(QSize(70, 70))
        self.lb_g6_right.setScaledContents(True)
        self.lb_g6_bg = QLabel(self.g6)
        self.lb_g6_bg.setObjectName(u"lb_g6_bg")
        self.lb_g6_bg.setGeometry(QRect(0, 19, 400, 90))
        self.lb_g6_bg.setMinimumSize(QSize(400, 90))
        self.lb_g6_bg.setMaximumSize(QSize(400, 110))
        self.lb_g6_bg.setScaledContents(True)
        self.lb_g6_bg.raise_()
        self.lb_g6_left.raise_()
        self.lb_g6_middle.raise_()
        self.lb_g6_right.raise_()
        self.g7 = QGroupBox(self.centralwidget)
        self.g7.setObjectName(u"g7")
        self.g7.setGeometry(QRect(10, 670, 400, 110))
        self.g7.setMinimumSize(QSize(400, 110))
        self.g7.setMaximumSize(QSize(400, 110))
        self.g7.setFont(font1)
        self.lb_g7_left = QLabel(self.g7)
        self.lb_g7_left.setObjectName(u"lb_g7_left")
        self.lb_g7_left.setGeometry(QRect(30, 30, 60, 60))
        self.lb_g7_left.setMinimumSize(QSize(55, 55))
        self.lb_g7_left.setMaximumSize(QSize(70, 70))
        self.lb_g7_left.setScaledContents(True)
        self.lb_g7_middle = QLabel(self.g7)
        self.lb_g7_middle.setObjectName(u"lb_g7_middle")
        self.lb_g7_middle.setGeometry(QRect(110, 20, 170, 81))
        sizePolicy.setHeightForWidth(self.lb_g7_middle.sizePolicy().hasHeightForWidth())
        self.lb_g7_middle.setSizePolicy(sizePolicy)
        self.lb_g7_middle.setMinimumSize(QSize(170, 70))
        self.lb_g7_middle.setMaximumSize(QSize(170, 90))
        self.lb_g7_middle.setScaledContents(True)
        self.lb_g7_middle.setWordWrap(True)
        self.lb_g7_right = QLabel(self.g7)
        self.lb_g7_right.setObjectName(u"lb_g7_right")
        self.lb_g7_right.setGeometry(QRect(310, 40, 50, 50))
        self.lb_g7_right.setMinimumSize(QSize(50, 50))
        self.lb_g7_right.setMaximumSize(QSize(70, 70))
        self.lb_g7_right.setScaledContents(True)
        self.lb_g7_bg = QLabel(self.g7)
        self.lb_g7_bg.setObjectName(u"lb_g7_bg")
        self.lb_g7_bg.setGeometry(QRect(0, 19, 400, 90))
        self.lb_g7_bg.setMinimumSize(QSize(400, 90))
        self.lb_g7_bg.setMaximumSize(QSize(400, 110))
        self.lb_g7_bg.setScaledContents(True)
        self.lb_g7_bg.raise_()
        self.lb_g7_left.raise_()
        self.lb_g7_middle.raise_()
        self.lb_g7_right.raise_()
        self.pbtn_next = QPushButton(self.centralwidget)
        self.pbtn_next.setObjectName(u"pbtn_next")
        self.pbtn_next.setGeometry(QRect(370, 790, 30, 30))
        self.pbtn_next.setMinimumSize(QSize(30, 30))
        self.pbtn_next.setMaximumSize(QSize(30, 30))
        self.pbtn_search = QPushButton(self.centralwidget)
        self.pbtn_search.setObjectName(u"pbtn_search")
        self.pbtn_search.setGeometry(QRect(20, 790, 30, 30))
        self.pbtn_search.setMinimumSize(QSize(30, 30))
        self.pbtn_search.setMaximumSize(QSize(30, 30))
        self.pbtn_refresh = QPushButton(self.centralwidget)
        self.pbtn_refresh.setObjectName(u"pbtn_refresh")
        self.pbtn_refresh.setGeometry(QRect(60, 790, 30, 30))
        self.pbtn_refresh.setMinimumSize(QSize(30, 30))
        self.pbtn_refresh.setMaximumSize(QSize(30, 30))
        wews.setCentralWidget(self.centralwidget)

        self.retranslateUi(wews)

        QMetaObject.connectSlotsByName(wews)
    # setupUi

    def retranslateUi(self, wews):
        wews.setWindowTitle(QCoreApplication.translate("wews", u"WEWS", None))
        self.lb_bg.setText("")
        self.lb_start.setText("")
        self.g1.setTitle("")
        self.lb_g1_left.setText("")
        self.lb_g1_middle.setText("")
        self.lb_g1_right.setText("")
        self.lb_g1_bg.setText("")
        self.g2.setTitle("")
        self.lb_g2_left.setText("")
        self.lb_g2_middle.setText("")
        self.lb_g2_right.setText("")
        self.lb_g2_bg.setText("")
        self.g3.setTitle("")
        self.lb_g3_left.setText("")
        self.lb_g3_middle.setText("")
        self.lb_g3_right.setText("")
        self.lb_g3_bg.setText("")
        self.g4.setTitle("")
        self.lb_g4_left.setText("")
        self.lb_g4_middle.setText("")
        self.lb_g4_right.setText("")
        self.lb_g4_bg.setText("")
        self.pbtn_last.setText("")
        self.g5.setTitle("")
        self.lb_g5_left.setText("")
        self.lb_g5_middle.setText("")
        self.lb_g5_right.setText("")
        self.lb_g5_bg.setText("")
        self.g6.setTitle("")
        self.lb_g6_left.setText("")
        self.lb_g6_middle.setText("")
        self.lb_g6_right.setText("")
        self.lb_g6_bg.setText("")
        self.g7.setTitle("")
        self.lb_g7_left.setText("")
        self.lb_g7_middle.setText("")
        self.lb_g7_right.setText("")
        self.lb_g7_bg.setText("")
        self.pbtn_next.setText("")
        self.pbtn_search.setText("")
        self.pbtn_refresh.setText("")
    # retranslateUi

